"""feat: add sources and posts tables

Revision ID: 647e0305ef21
Revises:
Create Date: 2026-09-19 15:12:43.087723

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "647e0305ef21"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("telegram", name="sourcetype"), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("from_location", sa.Text(), nullable=True),
        sa.Column("to_location", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_per_km", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new", "ready", "distributed", "skipped", "failed", "duplicate", name="poststatus"
            ),
            nullable=False,
        ),
        sa.Column("from_norm", sa.Text(), nullable=True),
        sa.Column("to_norm", sa.Text(), nullable=True),
        sa.Column("duplicate_of_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"], ["posts.id"], name=op.f("fk_posts_duplicate_of_id_posts")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_posts_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_posts_source_id_external_id")
        ),
    )
    op.create_index(
        op.f("ix_posts_fingerprint_posts_published_at"),
        "posts",
        ["fingerprint", "published_at"],
        unique=False,
    )
    op.create_index(op.f("ix_posts_status"), "posts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_status"), table_name="posts")
    op.drop_index(op.f("ix_posts_fingerprint_posts_published_at"), table_name="posts")
    op.drop_table("posts")
    op.drop_table("sources")
    # ### end Alembic commands ###
